version: '3.3'

networks:
    apimatemapnet:

services:
  SqlServerDb:
    container_name: SqlServerContainer
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
        - 1433:1433
    environment:
        - ACCEPT_EULA=Y
        - MSSQL_SA_PASSWORD=thiago@123
    networks:
        - apimatemapnet

#   PostgresDb:
#     container_name: PostgresContainer
#     image: postgres
#     ports:
#         - "5432:5432"
#     environment:
#         - POSTGRES_USER=thiago
#         - POSTGRES_PASSWORD=thiago@123
#         - POSTGRES_DB=MateMap
#     networks:
#         - apimatemapnet

  apimatemap:
    container_name: apimatemap
    image: thiagocleite91/apimatemap
    ports:
        - 8080:8080
    depends_on:
        - SqlServerDb
    networks:
        - apimatemapnet